name: Test
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  ci:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15, ubuntu-20.04, windows-2019]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.3.4

      - name: Setup Java 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt-openj9'
          java-version: '11'

      - name: Run Unit & Functional Tests
        run: |
          if [ "$RUNNER_OS" = "Windows" ]; then
            ./gradlew.bat clean check
          else
            ./gradlew clean check
          fi
        shell: bash