name: Test
on:
  push:
    branches: [ main, f-simple-javaExec-task-alternative ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15, ubuntu-20.04, windows-2019]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.3.4

      - name: Run Tests
        run: |
          if [ "$RUNNER_OS" = "Windows" ]; then
            gradlew.bat clean check
          else
            ./gradlew clean check
          fi